name: example
description: Example using thumper

version: 1.0.1

# This is an unpublishable example with intentional path dependencies.
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  thumper_bloc:
    path: ../../thumper_bloc
  flutter:
    sdk: flutter
  thumper:
    path: ../

dev_dependencies:
  lints: ^1.0.1

flutter:
  uses-material-design: true
