name: thumper
description: Widget for controlling an Iterable. Shows reset, forward step, play, pause and frequency controls.
version: 2.2.0
homepage: https://github.com/monopole/thumper

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  meta: ^1.7.0
  equatable: ^2.0.3
  bloc: ^8.0.3
  logging: ^1.0.2

dev_dependencies:
  bloc_test: ^9.0.3
  test: ^1.20.2
  lints: ^1.0.1

flutter:
  uses-material-design: true
