name: thumper
description: Widget for controlling an Iterable. Shows reset, forward step, play, pause and speed controls.
version: 0.1.8
homepage: https://github.com/monopole/thumper

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bloc: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  test: ^1.14.2
  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
