name: thumper
description: Widget for controlling an Iterable. Shows reset, forward step, play, pause and frequency controls.
version: 2.1.1
homepage: https://github.com/monopole/thumper

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  thumper_bloc:
    path: ../thumper_bloc
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  meta: ^1.7.0

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
